"""Pre-populated games database with popular titles for each system."""

# This database provides a starting catalog so users can browse games
# even before searching Internet Archive.

GAMES_DATABASE = {
    # ========== NES ==========
    "nes": [
        {"title": "Super Mario Bros.", "genre": "Platformer", "year": 1985, "publisher": "Nintendo"},
        {"title": "Super Mario Bros. 2", "genre": "Platformer", "year": 1988, "publisher": "Nintendo"},
        {"title": "Super Mario Bros. 3", "genre": "Platformer", "year": 1988, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda", "genre": "Action-Adventure", "year": 1986, "publisher": "Nintendo"},
        {"title": "Zelda II: The Adventure of Link", "genre": "Action-Adventure", "year": 1987, "publisher": "Nintendo"},
        {"title": "Metroid", "genre": "Action-Adventure", "year": 1986, "publisher": "Nintendo"},
        {"title": "Mega Man", "genre": "Platformer", "year": 1987, "publisher": "Capcom"},
        {"title": "Mega Man 2", "genre": "Platformer", "year": 1988, "publisher": "Capcom"},
        {"title": "Mega Man 3", "genre": "Platformer", "year": 1990, "publisher": "Capcom"},
        {"title": "Castlevania", "genre": "Platformer", "year": 1986, "publisher": "Konami"},
        {"title": "Castlevania II: Simon's Quest", "genre": "Action-Adventure", "year": 1987, "publisher": "Konami"},
        {"title": "Castlevania III: Dracula's Curse", "genre": "Platformer", "year": 1989, "publisher": "Konami"},
        {"title": "Contra", "genre": "Shooter", "year": 1988, "publisher": "Konami"},
        {"title": "Double Dragon", "genre": "Beat 'em Up", "year": 1988, "publisher": "Technos"},
        {"title": "Ninja Gaiden", "genre": "Platformer", "year": 1988, "publisher": "Tecmo"},
        {"title": "Final Fantasy", "genre": "RPG", "year": 1987, "publisher": "Square"},
        {"title": "Dragon Quest", "genre": "RPG", "year": 1986, "publisher": "Enix"},
        {"title": "Punch-Out!!", "genre": "Sports", "year": 1987, "publisher": "Nintendo"},
        {"title": "Tetris", "genre": "Puzzle", "year": 1989, "publisher": "Nintendo"},
        {"title": "Kirby's Adventure", "genre": "Platformer", "year": 1993, "publisher": "Nintendo"},
        {"title": "DuckTales", "genre": "Platformer", "year": 1989, "publisher": "Capcom"},
        {"title": "Battletoads", "genre": "Beat 'em Up", "year": 1991, "publisher": "Rare"},
        {"title": "Excitebike", "genre": "Racing", "year": 1984, "publisher": "Nintendo"},
        {"title": "Kid Icarus", "genre": "Platformer", "year": 1986, "publisher": "Nintendo"},
        {"title": "Ghosts 'n Goblins", "genre": "Platformer", "year": 1986, "publisher": "Capcom"},
    ],

    # ========== SNES ==========
    "snes": [
        {"title": "Super Mario World", "genre": "Platformer", "year": 1990, "publisher": "Nintendo"},
        {"title": "Super Mario World 2: Yoshi's Island", "genre": "Platformer", "year": 1995, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: A Link to the Past", "genre": "Action-Adventure", "year": 1991, "publisher": "Nintendo"},
        {"title": "Super Metroid", "genre": "Action-Adventure", "year": 1994, "publisher": "Nintendo"},
        {"title": "Chrono Trigger", "genre": "RPG", "year": 1995, "publisher": "Square"},
        {"title": "Final Fantasy IV", "genre": "RPG", "year": 1991, "publisher": "Square"},
        {"title": "Final Fantasy VI", "genre": "RPG", "year": 1994, "publisher": "Square"},
        {"title": "Secret of Mana", "genre": "RPG", "year": 1993, "publisher": "Square"},
        {"title": "EarthBound", "genre": "RPG", "year": 1994, "publisher": "Nintendo"},
        {"title": "Super Mario Kart", "genre": "Racing", "year": 1992, "publisher": "Nintendo"},
        {"title": "F-Zero", "genre": "Racing", "year": 1990, "publisher": "Nintendo"},
        {"title": "Donkey Kong Country", "genre": "Platformer", "year": 1994, "publisher": "Nintendo"},
        {"title": "Donkey Kong Country 2", "genre": "Platformer", "year": 1995, "publisher": "Nintendo"},
        {"title": "Donkey Kong Country 3", "genre": "Platformer", "year": 1996, "publisher": "Nintendo"},
        {"title": "Street Fighter II", "genre": "Fighting", "year": 1992, "publisher": "Capcom"},
        {"title": "Mega Man X", "genre": "Platformer", "year": 1993, "publisher": "Capcom"},
        {"title": "Mega Man X2", "genre": "Platformer", "year": 1994, "publisher": "Capcom"},
        {"title": "Mega Man X3", "genre": "Platformer", "year": 1995, "publisher": "Capcom"},
        {"title": "Super Castlevania IV", "genre": "Platformer", "year": 1991, "publisher": "Konami"},
        {"title": "Contra III: The Alien Wars", "genre": "Shooter", "year": 1992, "publisher": "Konami"},
        {"title": "Star Fox", "genre": "Shooter", "year": 1993, "publisher": "Nintendo"},
        {"title": "Kirby Super Star", "genre": "Platformer", "year": 1996, "publisher": "Nintendo"},
        {"title": "Super Mario RPG", "genre": "RPG", "year": 1996, "publisher": "Nintendo"},
        {"title": "Terranigma", "genre": "RPG", "year": 1995, "publisher": "Enix"},
        {"title": "ActRaiser", "genre": "Platformer", "year": 1990, "publisher": "Enix"},
    ],

    # ========== N64 ==========
    "n64": [
        {"title": "Super Mario 64", "genre": "Platformer", "year": 1996, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Ocarina of Time", "genre": "Action-Adventure", "year": 1998, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Majora's Mask", "genre": "Action-Adventure", "year": 2000, "publisher": "Nintendo"},
        {"title": "Mario Kart 64", "genre": "Racing", "year": 1996, "publisher": "Nintendo"},
        {"title": "GoldenEye 007", "genre": "Shooter", "year": 1997, "publisher": "Nintendo"},
        {"title": "Super Smash Bros.", "genre": "Fighting", "year": 1999, "publisher": "Nintendo"},
        {"title": "Banjo-Kazooie", "genre": "Platformer", "year": 1998, "publisher": "Nintendo"},
        {"title": "Banjo-Tooie", "genre": "Platformer", "year": 2000, "publisher": "Nintendo"},
        {"title": "Donkey Kong 64", "genre": "Platformer", "year": 1999, "publisher": "Nintendo"},
        {"title": "Paper Mario", "genre": "RPG", "year": 2000, "publisher": "Nintendo"},
        {"title": "Star Fox 64", "genre": "Shooter", "year": 1997, "publisher": "Nintendo"},
        {"title": "F-Zero X", "genre": "Racing", "year": 1998, "publisher": "Nintendo"},
        {"title": "Wave Race 64", "genre": "Racing", "year": 1996, "publisher": "Nintendo"},
        {"title": "Perfect Dark", "genre": "Shooter", "year": 2000, "publisher": "Rare"},
        {"title": "Conker's Bad Fur Day", "genre": "Platformer", "year": 2001, "publisher": "Rare"},
        {"title": "Pokemon Stadium", "genre": "Strategy", "year": 1999, "publisher": "Nintendo"},
        {"title": "Pokemon Stadium 2", "genre": "Strategy", "year": 2000, "publisher": "Nintendo"},
        {"title": "Kirby 64: The Crystal Shards", "genre": "Platformer", "year": 2000, "publisher": "Nintendo"},
        {"title": "Yoshi's Story", "genre": "Platformer", "year": 1997, "publisher": "Nintendo"},
        {"title": "Diddy Kong Racing", "genre": "Racing", "year": 1997, "publisher": "Rare"},
    ],

    # ========== GameCube ==========
    "gcn": [
        {"title": "Super Mario Sunshine", "genre": "Platformer", "year": 2002, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: The Wind Waker", "genre": "Action-Adventure", "year": 2002, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Twilight Princess", "genre": "Action-Adventure", "year": 2006, "publisher": "Nintendo"},
        {"title": "Metroid Prime", "genre": "Action-Adventure", "year": 2002, "publisher": "Nintendo"},
        {"title": "Metroid Prime 2: Echoes", "genre": "Action-Adventure", "year": 2004, "publisher": "Nintendo"},
        {"title": "Super Smash Bros. Melee", "genre": "Fighting", "year": 2001, "publisher": "Nintendo"},
        {"title": "Mario Kart: Double Dash!!", "genre": "Racing", "year": 2003, "publisher": "Nintendo"},
        {"title": "Luigi's Mansion", "genre": "Action-Adventure", "year": 2001, "publisher": "Nintendo"},
        {"title": "Paper Mario: The Thousand-Year Door", "genre": "RPG", "year": 2004, "publisher": "Nintendo"},
        {"title": "F-Zero GX", "genre": "Racing", "year": 2003, "publisher": "Nintendo"},
        {"title": "Star Fox Adventures", "genre": "Action-Adventure", "year": 2002, "publisher": "Nintendo"},
        {"title": "Pikmin", "genre": "Strategy", "year": 2001, "publisher": "Nintendo"},
        {"title": "Pikmin 2", "genre": "Strategy", "year": 2004, "publisher": "Nintendo"},
        {"title": "Animal Crossing", "genre": "Simulation", "year": 2001, "publisher": "Nintendo"},
        {"title": "Resident Evil 4", "genre": "Horror", "year": 2005, "publisher": "Capcom"},
        {"title": "Tales of Symphonia", "genre": "RPG", "year": 2003, "publisher": "Namco"},
        {"title": "Sonic Adventure 2 Battle", "genre": "Platformer", "year": 2001, "publisher": "Sega"},
        {"title": "Eternal Darkness", "genre": "Horror", "year": 2002, "publisher": "Nintendo"},
        {"title": "Fire Emblem: Path of Radiance", "genre": "Strategy", "year": 2005, "publisher": "Nintendo"},
        {"title": "Mario Party 4", "genre": "Party", "year": 2002, "publisher": "Nintendo"},
    ],

    # ========== Game Boy ==========
    "gb": [
        {"title": "Pokemon Red", "genre": "RPG", "year": 1996, "publisher": "Nintendo"},
        {"title": "Pokemon Blue", "genre": "RPG", "year": 1996, "publisher": "Nintendo"},
        {"title": "Pokemon Yellow", "genre": "RPG", "year": 1998, "publisher": "Nintendo"},
        {"title": "Tetris", "genre": "Puzzle", "year": 1989, "publisher": "Nintendo"},
        {"title": "Super Mario Land", "genre": "Platformer", "year": 1989, "publisher": "Nintendo"},
        {"title": "Super Mario Land 2", "genre": "Platformer", "year": 1992, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Link's Awakening", "genre": "Action-Adventure", "year": 1993, "publisher": "Nintendo"},
        {"title": "Kirby's Dream Land", "genre": "Platformer", "year": 1992, "publisher": "Nintendo"},
        {"title": "Kirby's Dream Land 2", "genre": "Platformer", "year": 1995, "publisher": "Nintendo"},
        {"title": "Metroid II: Return of Samus", "genre": "Action-Adventure", "year": 1991, "publisher": "Nintendo"},
        {"title": "Mega Man: Dr. Wily's Revenge", "genre": "Platformer", "year": 1991, "publisher": "Capcom"},
        {"title": "Donkey Kong Land", "genre": "Platformer", "year": 1995, "publisher": "Nintendo"},
        {"title": "Wario Land: Super Mario Land 3", "genre": "Platformer", "year": 1994, "publisher": "Nintendo"},
        {"title": "Final Fantasy Legend", "genre": "RPG", "year": 1989, "publisher": "Square"},
        {"title": "Final Fantasy Adventure", "genre": "RPG", "year": 1991, "publisher": "Square"},
    ],

    # ========== Game Boy Color ==========
    "gbc": [
        {"title": "Pokemon Gold", "genre": "RPG", "year": 1999, "publisher": "Nintendo"},
        {"title": "Pokemon Silver", "genre": "RPG", "year": 1999, "publisher": "Nintendo"},
        {"title": "Pokemon Crystal", "genre": "RPG", "year": 2000, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Oracle of Ages", "genre": "Action-Adventure", "year": 2001, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Oracle of Seasons", "genre": "Action-Adventure", "year": 2001, "publisher": "Nintendo"},
        {"title": "Dragon Quest III", "genre": "RPG", "year": 2000, "publisher": "Enix"},
        {"title": "Wario Land 2", "genre": "Platformer", "year": 1998, "publisher": "Nintendo"},
        {"title": "Wario Land 3", "genre": "Platformer", "year": 2000, "publisher": "Nintendo"},
        {"title": "Metal Gear Solid", "genre": "Action", "year": 2000, "publisher": "Konami"},
        {"title": "Mario Golf", "genre": "Sports", "year": 1999, "publisher": "Nintendo"},
        {"title": "Mario Tennis", "genre": "Sports", "year": 2000, "publisher": "Nintendo"},
        {"title": "Shantae", "genre": "Platformer", "year": 2002, "publisher": "Capcom"},
        {"title": "Mega Man Xtreme", "genre": "Platformer", "year": 2000, "publisher": "Capcom"},
        {"title": "Dragon Quest Monsters", "genre": "RPG", "year": 1998, "publisher": "Enix"},
        {"title": "Harvest Moon GBC", "genre": "Simulation", "year": 1999, "publisher": "Natsume"},
    ],

    # ========== Game Boy Advance ==========
    "gba": [
        {"title": "Pokemon Ruby", "genre": "RPG", "year": 2002, "publisher": "Nintendo"},
        {"title": "Pokemon Sapphire", "genre": "RPG", "year": 2002, "publisher": "Nintendo"},
        {"title": "Pokemon Emerald", "genre": "RPG", "year": 2004, "publisher": "Nintendo"},
        {"title": "Pokemon FireRed", "genre": "RPG", "year": 2004, "publisher": "Nintendo"},
        {"title": "Pokemon LeafGreen", "genre": "RPG", "year": 2004, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: The Minish Cap", "genre": "Action-Adventure", "year": 2004, "publisher": "Nintendo"},
        {"title": "Metroid Fusion", "genre": "Action-Adventure", "year": 2002, "publisher": "Nintendo"},
        {"title": "Metroid: Zero Mission", "genre": "Action-Adventure", "year": 2004, "publisher": "Nintendo"},
        {"title": "Final Fantasy Tactics Advance", "genre": "Strategy", "year": 2003, "publisher": "Square"},
        {"title": "Golden Sun", "genre": "RPG", "year": 2001, "publisher": "Nintendo"},
        {"title": "Golden Sun: The Lost Age", "genre": "RPG", "year": 2002, "publisher": "Nintendo"},
        {"title": "Fire Emblem", "genre": "Strategy", "year": 2003, "publisher": "Nintendo"},
        {"title": "Fire Emblem: The Sacred Stones", "genre": "Strategy", "year": 2004, "publisher": "Nintendo"},
        {"title": "Advance Wars", "genre": "Strategy", "year": 2001, "publisher": "Nintendo"},
        {"title": "Advance Wars 2", "genre": "Strategy", "year": 2003, "publisher": "Nintendo"},
        {"title": "Castlevania: Aria of Sorrow", "genre": "Action-Adventure", "year": 2003, "publisher": "Konami"},
        {"title": "Castlevania: Circle of the Moon", "genre": "Action-Adventure", "year": 2001, "publisher": "Konami"},
        {"title": "Mega Man Zero", "genre": "Platformer", "year": 2002, "publisher": "Capcom"},
        {"title": "Super Mario Advance", "genre": "Platformer", "year": 2001, "publisher": "Nintendo"},
        {"title": "Mario & Luigi: Superstar Saga", "genre": "RPG", "year": 2003, "publisher": "Nintendo"},
        {"title": "Wario Land 4", "genre": "Platformer", "year": 2001, "publisher": "Nintendo"},
        {"title": "Kirby & The Amazing Mirror", "genre": "Platformer", "year": 2004, "publisher": "Nintendo"},
        {"title": "Sonic Advance", "genre": "Platformer", "year": 2001, "publisher": "Sega"},
        {"title": "Kingdom Hearts: Chain of Memories", "genre": "RPG", "year": 2004, "publisher": "Square Enix"},
        {"title": "Final Fantasy VI Advance", "genre": "RPG", "year": 2006, "publisher": "Square Enix"},
    ],

    # ========== Nintendo DS ==========
    "nds": [
        {"title": "Pokemon Diamond", "genre": "RPG", "year": 2006, "publisher": "Nintendo"},
        {"title": "Pokemon Pearl", "genre": "RPG", "year": 2006, "publisher": "Nintendo"},
        {"title": "Pokemon Platinum", "genre": "RPG", "year": 2008, "publisher": "Nintendo"},
        {"title": "Pokemon HeartGold", "genre": "RPG", "year": 2009, "publisher": "Nintendo"},
        {"title": "Pokemon SoulSilver", "genre": "RPG", "year": 2009, "publisher": "Nintendo"},
        {"title": "Pokemon Black", "genre": "RPG", "year": 2010, "publisher": "Nintendo"},
        {"title": "Pokemon White", "genre": "RPG", "year": 2010, "publisher": "Nintendo"},
        {"title": "New Super Mario Bros.", "genre": "Platformer", "year": 2006, "publisher": "Nintendo"},
        {"title": "Super Mario 64 DS", "genre": "Platformer", "year": 2004, "publisher": "Nintendo"},
        {"title": "Mario Kart DS", "genre": "Racing", "year": 2005, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Phantom Hourglass", "genre": "Action-Adventure", "year": 2007, "publisher": "Nintendo"},
        {"title": "The Legend of Zelda: Spirit Tracks", "genre": "Action-Adventure", "year": 2009, "publisher": "Nintendo"},
        {"title": "Animal Crossing: Wild World", "genre": "Simulation", "year": 2005, "publisher": "Nintendo"},
        {"title": "Chrono Trigger", "genre": "RPG", "year": 2008, "publisher": "Square Enix"},
        {"title": "Dragon Quest IX", "genre": "RPG", "year": 2009, "publisher": "Square Enix"},
        {"title": "Fire Emblem: Shadow Dragon", "genre": "Strategy", "year": 2008, "publisher": "Nintendo"},
        {"title": "Advance Wars: Dual Strike", "genre": "Strategy", "year": 2005, "publisher": "Nintendo"},
        {"title": "Phoenix Wright: Ace Attorney", "genre": "Adventure", "year": 2005, "publisher": "Capcom"},
        {"title": "Professor Layton and the Curious Village", "genre": "Puzzle", "year": 2007, "publisher": "Level-5"},
        {"title": "The World Ends with You", "genre": "RPG", "year": 2007, "publisher": "Square Enix"},
    ],

    # ========== PlayStation ==========
    "ps1": [
        {"title": "Final Fantasy VII", "genre": "RPG", "year": 1997, "publisher": "Square"},
        {"title": "Final Fantasy VIII", "genre": "RPG", "year": 1999, "publisher": "Square"},
        {"title": "Final Fantasy IX", "genre": "RPG", "year": 2000, "publisher": "Square"},
        {"title": "Metal Gear Solid", "genre": "Action", "year": 1998, "publisher": "Konami"},
        {"title": "Resident Evil", "genre": "Horror", "year": 1996, "publisher": "Capcom"},
        {"title": "Resident Evil 2", "genre": "Horror", "year": 1998, "publisher": "Capcom"},
        {"title": "Resident Evil 3: Nemesis", "genre": "Horror", "year": 1999, "publisher": "Capcom"},
        {"title": "Silent Hill", "genre": "Horror", "year": 1999, "publisher": "Konami"},
        {"title": "Castlevania: Symphony of the Night", "genre": "Action-Adventure", "year": 1997, "publisher": "Konami"},
        {"title": "Crash Bandicoot", "genre": "Platformer", "year": 1996, "publisher": "Sony"},
        {"title": "Crash Bandicoot 2", "genre": "Platformer", "year": 1997, "publisher": "Sony"},
        {"title": "Crash Bandicoot 3: Warped", "genre": "Platformer", "year": 1998, "publisher": "Sony"},
        {"title": "Spyro the Dragon", "genre": "Platformer", "year": 1998, "publisher": "Sony"},
        {"title": "Spyro 2: Ripto's Rage!", "genre": "Platformer", "year": 1999, "publisher": "Sony"},
        {"title": "Gran Turismo", "genre": "Racing", "year": 1997, "publisher": "Sony"},
        {"title": "Gran Turismo 2", "genre": "Racing", "year": 1999, "publisher": "Sony"},
        {"title": "Tekken 3", "genre": "Fighting", "year": 1998, "publisher": "Namco"},
        {"title": "Tony Hawk's Pro Skater 2", "genre": "Sports", "year": 2000, "publisher": "Activision"},
        {"title": "Chrono Cross", "genre": "RPG", "year": 1999, "publisher": "Square"},
        {"title": "Xenogears", "genre": "RPG", "year": 1998, "publisher": "Square"},
        {"title": "Suikoden II", "genre": "RPG", "year": 1998, "publisher": "Konami"},
        {"title": "Vagrant Story", "genre": "RPG", "year": 2000, "publisher": "Square"},
        {"title": "Parasite Eve", "genre": "RPG", "year": 1998, "publisher": "Square"},
        {"title": "Legend of Dragoon", "genre": "RPG", "year": 1999, "publisher": "Sony"},
        {"title": "Medievil", "genre": "Action-Adventure", "year": 1998, "publisher": "Sony"},
    ],

    # ========== PlayStation 2 ==========
    "ps2": [
        {"title": "Grand Theft Auto: San Andreas", "genre": "Action", "year": 2004, "publisher": "Rockstar"},
        {"title": "Grand Theft Auto: Vice City", "genre": "Action", "year": 2002, "publisher": "Rockstar"},
        {"title": "Grand Theft Auto III", "genre": "Action", "year": 2001, "publisher": "Rockstar"},
        {"title": "Final Fantasy X", "genre": "RPG", "year": 2001, "publisher": "Square"},
        {"title": "Final Fantasy XII", "genre": "RPG", "year": 2006, "publisher": "Square Enix"},
        {"title": "Kingdom Hearts", "genre": "RPG", "year": 2002, "publisher": "Square"},
        {"title": "Kingdom Hearts II", "genre": "RPG", "year": 2005, "publisher": "Square Enix"},
        {"title": "Metal Gear Solid 2: Sons of Liberty", "genre": "Action", "year": 2001, "publisher": "Konami"},
        {"title": "Metal Gear Solid 3: Snake Eater", "genre": "Action", "year": 2004, "publisher": "Konami"},
        {"title": "Shadow of the Colossus", "genre": "Action-Adventure", "year": 2005, "publisher": "Sony"},
        {"title": "Ico", "genre": "Action-Adventure", "year": 2001, "publisher": "Sony"},
        {"title": "God of War", "genre": "Action", "year": 2005, "publisher": "Sony"},
        {"title": "God of War II", "genre": "Action", "year": 2007, "publisher": "Sony"},
        {"title": "Devil May Cry", "genre": "Action", "year": 2001, "publisher": "Capcom"},
        {"title": "Devil May Cry 3", "genre": "Action", "year": 2005, "publisher": "Capcom"},
        {"title": "Resident Evil 4", "genre": "Horror", "year": 2005, "publisher": "Capcom"},
        {"title": "Silent Hill 2", "genre": "Horror", "year": 2001, "publisher": "Konami"},
        {"title": "Silent Hill 3", "genre": "Horror", "year": 2003, "publisher": "Konami"},
        {"title": "Persona 3 FES", "genre": "RPG", "year": 2007, "publisher": "Atlus"},
        {"title": "Persona 4", "genre": "RPG", "year": 2008, "publisher": "Atlus"},
        {"title": "Ratchet & Clank", "genre": "Platformer", "year": 2002, "publisher": "Sony"},
        {"title": "Jak and Daxter", "genre": "Platformer", "year": 2001, "publisher": "Sony"},
        {"title": "Sly Cooper", "genre": "Platformer", "year": 2002, "publisher": "Sony"},
        {"title": "Gran Turismo 3", "genre": "Racing", "year": 2001, "publisher": "Sony"},
        {"title": "Gran Turismo 4", "genre": "Racing", "year": 2004, "publisher": "Sony"},
    ],

    # ========== Genesis ==========
    "genesis": [
        {"title": "Sonic the Hedgehog", "genre": "Platformer", "year": 1991, "publisher": "Sega"},
        {"title": "Sonic the Hedgehog 2", "genre": "Platformer", "year": 1992, "publisher": "Sega"},
        {"title": "Sonic the Hedgehog 3", "genre": "Platformer", "year": 1994, "publisher": "Sega"},
        {"title": "Sonic & Knuckles", "genre": "Platformer", "year": 1994, "publisher": "Sega"},
        {"title": "Streets of Rage", "genre": "Beat 'em Up", "year": 1991, "publisher": "Sega"},
        {"title": "Streets of Rage 2", "genre": "Beat 'em Up", "year": 1992, "publisher": "Sega"},
        {"title": "Streets of Rage 3", "genre": "Beat 'em Up", "year": 1994, "publisher": "Sega"},
        {"title": "Golden Axe", "genre": "Beat 'em Up", "year": 1989, "publisher": "Sega"},
        {"title": "Phantasy Star IV", "genre": "RPG", "year": 1993, "publisher": "Sega"},
        {"title": "Shining Force", "genre": "Strategy", "year": 1992, "publisher": "Sega"},
        {"title": "Shining Force II", "genre": "Strategy", "year": 1993, "publisher": "Sega"},
        {"title": "Gunstar Heroes", "genre": "Shooter", "year": 1993, "publisher": "Sega"},
        {"title": "Contra: Hard Corps", "genre": "Shooter", "year": 1994, "publisher": "Konami"},
        {"title": "Castlevania: Bloodlines", "genre": "Platformer", "year": 1994, "publisher": "Konami"},
        {"title": "Shinobi III", "genre": "Platformer", "year": 1993, "publisher": "Sega"},
        {"title": "Comix Zone", "genre": "Beat 'em Up", "year": 1995, "publisher": "Sega"},
        {"title": "Vectorman", "genre": "Platformer", "year": 1995, "publisher": "Sega"},
        {"title": "Earthworm Jim", "genre": "Platformer", "year": 1994, "publisher": "Shiny"},
        {"title": "Aladdin", "genre": "Platformer", "year": 1993, "publisher": "Sega"},
        {"title": "Mortal Kombat II", "genre": "Fighting", "year": 1994, "publisher": "Acclaim"},
    ],

    # ========== Dreamcast ==========
    "dreamcast": [
        {"title": "Sonic Adventure", "genre": "Platformer", "year": 1998, "publisher": "Sega"},
        {"title": "Sonic Adventure 2", "genre": "Platformer", "year": 2001, "publisher": "Sega"},
        {"title": "Shenmue", "genre": "Action-Adventure", "year": 1999, "publisher": "Sega"},
        {"title": "Shenmue II", "genre": "Action-Adventure", "year": 2001, "publisher": "Sega"},
        {"title": "Crazy Taxi", "genre": "Racing", "year": 1999, "publisher": "Sega"},
        {"title": "Jet Set Radio", "genre": "Action", "year": 2000, "publisher": "Sega"},
        {"title": "Soul Calibur", "genre": "Fighting", "year": 1999, "publisher": "Namco"},
        {"title": "Power Stone", "genre": "Fighting", "year": 1999, "publisher": "Capcom"},
        {"title": "Marvel vs. Capcom 2", "genre": "Fighting", "year": 2000, "publisher": "Capcom"},
        {"title": "Resident Evil: Code Veronica", "genre": "Horror", "year": 2000, "publisher": "Capcom"},
        {"title": "Skies of Arcadia", "genre": "RPG", "year": 2000, "publisher": "Sega"},
        {"title": "Grandia II", "genre": "RPG", "year": 2000, "publisher": "Game Arts"},
        {"title": "Phantasy Star Online", "genre": "RPG", "year": 2000, "publisher": "Sega"},
        {"title": "Dead or Alive 2", "genre": "Fighting", "year": 2000, "publisher": "Tecmo"},
        {"title": "Sega Rally 2", "genre": "Racing", "year": 1999, "publisher": "Sega"},
    ],

    # ========== Saturn ==========
    "saturn": [
        {"title": "Panzer Dragoon Saga", "genre": "RPG", "year": 1998, "publisher": "Sega"},
        {"title": "Panzer Dragoon II Zwei", "genre": "Shooter", "year": 1996, "publisher": "Sega"},
        {"title": "Nights into Dreams", "genre": "Action", "year": 1996, "publisher": "Sega"},
        {"title": "Virtua Fighter 2", "genre": "Fighting", "year": 1995, "publisher": "Sega"},
        {"title": "Guardian Heroes", "genre": "Beat 'em Up", "year": 1996, "publisher": "Sega"},
        {"title": "Shining Force III", "genre": "Strategy", "year": 1997, "publisher": "Sega"},
        {"title": "Radiant Silvergun", "genre": "Shooter", "year": 1998, "publisher": "Treasure"},
        {"title": "Dragon Force", "genre": "Strategy", "year": 1996, "publisher": "Working Designs"},
        {"title": "Burning Rangers", "genre": "Action", "year": 1998, "publisher": "Sega"},
        {"title": "Street Fighter Alpha 3", "genre": "Fighting", "year": 1998, "publisher": "Capcom"},
    ],

    # ========== Master System ==========
    "sms": [
        {"title": "Alex Kidd in Miracle World", "genre": "Platformer", "year": 1986, "publisher": "Sega"},
        {"title": "Phantasy Star", "genre": "RPG", "year": 1987, "publisher": "Sega"},
        {"title": "Wonder Boy III: The Dragon's Trap", "genre": "Action-Adventure", "year": 1989, "publisher": "Sega"},
        {"title": "Sonic the Hedgehog", "genre": "Platformer", "year": 1991, "publisher": "Sega"},
        {"title": "Castle of Illusion", "genre": "Platformer", "year": 1990, "publisher": "Sega"},
        {"title": "Shinobi", "genre": "Action", "year": 1988, "publisher": "Sega"},
        {"title": "Golden Axe Warrior", "genre": "Action-Adventure", "year": 1991, "publisher": "Sega"},
    ],

    # ========== Game Gear ==========
    "gamegear": [
        {"title": "Sonic the Hedgehog", "genre": "Platformer", "year": 1991, "publisher": "Sega"},
        {"title": "Sonic the Hedgehog 2", "genre": "Platformer", "year": 1992, "publisher": "Sega"},
        {"title": "Columns", "genre": "Puzzle", "year": 1990, "publisher": "Sega"},
        {"title": "Shinobi", "genre": "Action", "year": 1991, "publisher": "Sega"},
        {"title": "Shining Force: The Sword of Hajya", "genre": "Strategy", "year": 1993, "publisher": "Sega"},
    ],

    # ========== TurboGrafx-16 ==========
    "tg16": [
        {"title": "Ys Book I & II", "genre": "RPG", "year": 1989, "publisher": "Hudson"},
        {"title": "Bonk's Adventure", "genre": "Platformer", "year": 1989, "publisher": "Hudson"},
        {"title": "Splatterhouse", "genre": "Beat 'em Up", "year": 1990, "publisher": "Namco"},
        {"title": "Blazing Lazers", "genre": "Shooter", "year": 1989, "publisher": "Hudson"},
        {"title": "Military Madness", "genre": "Strategy", "year": 1989, "publisher": "Hudson"},
        {"title": "Castlevania: Rondo of Blood", "genre": "Platformer", "year": 1993, "publisher": "Konami"},
        {"title": "Lords of Thunder", "genre": "Shooter", "year": 1993, "publisher": "Hudson"},
    ],

    # ========== Neo Geo ==========
    "neogeo": [
        {"title": "Metal Slug", "genre": "Shooter", "year": 1996, "publisher": "SNK"},
        {"title": "Metal Slug 2", "genre": "Shooter", "year": 1998, "publisher": "SNK"},
        {"title": "Metal Slug 3", "genre": "Shooter", "year": 2000, "publisher": "SNK"},
        {"title": "King of Fighters '98", "genre": "Fighting", "year": 1998, "publisher": "SNK"},
        {"title": "Samurai Shodown II", "genre": "Fighting", "year": 1994, "publisher": "SNK"},
        {"title": "Garou: Mark of the Wolves", "genre": "Fighting", "year": 1999, "publisher": "SNK"},
        {"title": "Last Blade 2", "genre": "Fighting", "year": 1998, "publisher": "SNK"},
        {"title": "Blazing Star", "genre": "Shooter", "year": 1998, "publisher": "Yumekobo"},
        {"title": "Pulstar", "genre": "Shooter", "year": 1995, "publisher": "Aicom"},
        {"title": "Windjammers", "genre": "Sports", "year": 1994, "publisher": "Data East"},
    ],

    # ========== Atari 2600 ==========
    "atari2600": [
        {"title": "Pitfall!", "genre": "Platformer", "year": 1982, "publisher": "Activision"},
        {"title": "Space Invaders", "genre": "Shooter", "year": 1980, "publisher": "Atari"},
        {"title": "Pac-Man", "genre": "Action", "year": 1982, "publisher": "Atari"},
        {"title": "Adventure", "genre": "Adventure", "year": 1980, "publisher": "Atari"},
        {"title": "River Raid", "genre": "Shooter", "year": 1982, "publisher": "Activision"},
        {"title": "Asteroids", "genre": "Shooter", "year": 1981, "publisher": "Atari"},
        {"title": "Missile Command", "genre": "Shooter", "year": 1981, "publisher": "Atari"},
        {"title": "Frogger", "genre": "Action", "year": 1982, "publisher": "Parker Brothers"},
        {"title": "Centipede", "genre": "Shooter", "year": 1982, "publisher": "Atari"},
        {"title": "Yars' Revenge", "genre": "Shooter", "year": 1982, "publisher": "Atari"},
    ],
}

# Function to get games for a system
def get_games_for_system(system_id: str) -> list:
    """Get the pre-populated games list for a system."""
    return GAMES_DATABASE.get(system_id, [])

# Function to get all games
def get_all_games() -> dict:
    """Get all pre-populated games."""
    return GAMES_DATABASE
